Double test timeout to 10 seconds, see https://github.com/josephfrazier/reported-web/actions/runs/21764969746/job/62798286058?pr=663
    FAIL src/getVehicleType.test.js (5.223 s)
      getVehicleType
        ✕ returns the right object (5001 ms)

      ● getVehicleType › returns the right object

        thrown: "Exceeded timeout of 5000 ms for a test.
        Add a timeout value to this test to increase the timeout, if this is a long-running test. See https://jestjs.io/docs/api#testname-fn-timeout."

           7 |
           8 | describe('getVehicleType', () => {
        >  9 |   test('returns the right object', async () => {
             |   ^
          10 |     const result = await getVehicleType({
          11 |       licensePlate: 'TEST',
          12 |       licenseState: 'NY',

          at test (src/getVehicleType.test.js:9:3)
          at Object.describe (src/getVehicleType.test.js:8:1)

    A worker process has failed to exit gracefully and has been force exited. This is likely caused by tests leaking due to improper teardown. Try running with --detectOpenHandles to find leaks. Active timers can also cause this, ensure that .unref() was called on them.
    Test Suites: 1 failed, 7 passed, 8 total
    Tests:       1 failed, 14 passed, 15 total
    Snapshots:   13 passed, 13 total
    Time:        9.109 s
    Ran all test suites.
    error Command failed with exit code 1.
    info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
    Error: Process completed with exit code 1.
    0s