Revert "build(deps-dev): bump webpack-dev-middleware from 3.7.3 to 7.4.5 (#692)" (#693)
This reverts commit bb5dcab58a059fe4002e9defc8bec70e69cdf8cb.

Reverts josephfrazier/reported-web#692

It broke `yarn start`:

```
$ yarn start
yarn run v1.22.22
$ node -r dotenv/config node_modules/.bin/babel-node tools/run start --inspect
Debugger listening on ws://127.0.0.1:9229/f6a437ed-9a80-4c1c-831d-8bba74b7dcd3
For help, see: https://nodejs.org/en/docs/inspector
[22:23:08] Starting 'start'...
[22:23:08] Starting 'clean'...
[22:23:08] Finished 'clean' after 8 ms
ValidationError: Invalid options object. Dev Middleware has been initialized using an options object that does not match the API schema.
 - options has an unknown property 'watchOptions'. These properties are valid:
   object { mimeTypes?, mimeTypeDefault?, writeToDisk?, methods?, headers?, publicPath?, stats?, serverSideRender?, outputFileSystem?, index?, modifyResponseData?, etag?, lastModified?, cacheControl?, cacheImmutable? }
    at validate (/Users/josephfrazier/workspace/reported-web/node_modules/webpack-dev-middleware/node_modules/schema-utils/dist/validate.js:213:11)
    at wdm (/Users/josephfrazier/workspace/reported-web/node_modules/webpack-dev-middleware/dist/index.js:199:3)
    at start (/Users/josephfrazier/workspace/reported-web/tools/start.js:123:25)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```