XXX DOES NOT WORK: Home.js: Use simpledotcss instead of marx-css
I get this error when I open localhost:3000

> # SyntaxError
>
> ```
> /Users/josephfrazier/workspace/reported-web/node_modules/simpledotcss/simple.css:2
> :root,
> ^
>
> SyntaxError: Unexpected token ':'
>     at Object.compileFunction (node:vm:360:18)
>     at wrapSafe (node:internal/modules/cjs/loader:1088:15)
>     at Module._compile (node:internal/modules/cjs/loader:1123:27)
>     at Module._extensions..js (node:internal/modules/cjs/loader:1213:10)
>     at Object.newLoader [as .js] (/Users/josephfrazier/workspace/reported-web/node_modules/pirates/lib/index.js:104:7)
>     at Module.load (node:internal/modules/cjs/loader:1037:32)
>     at Function.Module._load (node:internal/modules/cjs/loader:878:12)
>     at Module.require (node:internal/modules/cjs/loader:1061:19)
>     at require (node:internal/modules/cjs/helpers:103:18)
>     at Object.simpledotcss (/Users/josephfrazier/workspace/reported-web/external commonjs "simpledotcss":1:1)
> ```